version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: mlops_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    restart: always

  master:
    container_name: mlops_master
    build:
      context: .
      dockerfile: master/Dockerfile
    volumes:
      - ./master:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always

volumes:
  postgres_data: